version: '3.8'

services:
  postgres :
    image: postgres:14-alpine

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
