version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15-alpine
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#      - ./configs/postgres.conf:/etc/postgresql/postgresql.conf
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres-data:
