version: '3.1'

services:
  postgres :
    image: postgres:14-alpine

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
